model:
  backbone:
    name: blip-v2
    trainable: False
  branch:
    name: simple_branch
  meta_arch:
    name: backbone_one_branch

dataset:
  image_dimension: [224,224]
  name: hier_ads

  hier_ads:
    annot_dir: # Path to the annotations directory
    distances_file: level_wise_lca_height.pkl
    
metrics: [accuracy, f1_score, precision, recall]
hier_metrics: ["lca_height_lw", "lca_height_mistakes_lw", "tie_lw", "tie_mistakes_lw"]

seed: 1
device: cuda:0

train:
  epochs: 40
  batch_size: 32
  dropout_p: 0.3
  lr: 0.0001
  loss_class: soft_labels_l

test:
  results_path: # /path/to/test_results.xlsx
  posthoc_methods: []
  batch_size: 32
  bet_on_leaf_level: False

loss_config:
  hxe_l:
    alpha_value: 0.3
    normalize: False
  barz_denzler_l:
    num_levels: 3
  soft_labels_l:
    beta_value: 15
  dot_l:
    pth_power: 3
  simple_ce_l:
    num_levels: 3

  sum_ce:
    num_levels: 3
  dot:
    pth_power: 3

wandb:
  unique_suffix: ''
  entity: # entity_name
  project: # project_name
  use_wandb: False

ckpt:
  save_ckpt: True
  ckptdir: # Path of directory for saving checkpoints
  ckptfreq: 2